//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlderWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public int id { get; set; }
        public string title { get; set; }
        public string coverImg { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public string genre { get; set; }
        public Nullable<byte> duration { get; set; }
        public Nullable<System.DateTime> careateDate { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
    }
}
